apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-api
  template:
    metadata:
      labels:
        app: rollout-api
    spec:
      containers:
        - name: rollout-api
          image: rollout-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rollout-api-configmap
                  key: DATABASE_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
          - mountPath: /data
            name: db-storage
        volumes:
        - name: db-storage
          persistentVolumeClaim:
          claimName: rollout-api-pv
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-api
spec:
  selector:
    app: rollout-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rollout-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollout-api-configmap
stringData:
  DATABASE_URL: "jdbc:sqlite:/data/rollout.db"
