apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-api
  template:
    metadata:
      labels:
        app: rollout-api
    spec:
      containers:
        - name: rollout-api
          image: rollout-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rollout-api-config
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-api
spec:
  selector:
    app: rollout-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rollout-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rollout-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollout-api-config
data:
  DATABASE_URL: "jdbc:sqlite:/data/rollout.db"
